---
- name: restart postgres
  ansible.builtin.systemd:
     name: postgresql@14-main
     state: restarted
     daemon_reload: yes
     enabled: yes
- name: restart sonarqube
  ansible.builtin.systemd:
     name: sonar
     state: restarted
     daemon_reload: yes
     enabled: yes